### ISSUE TITLE
 PHP Warning – yii\base\ErrorException 

### ISSUE THREAD

**Issue by myname1614** [akbarjoudi/yii2-bot-telegram#16]
```
[error][yii\base\ErrorException:2] yii\base\ErrorException: Invalid argument supplied for foreach() in vendor/yiisoft/yii2/BaseYii.php:557
Stack trace:
#0 vendor/yiisoft/yii2/BaseYii.php(557): yii\web\ErrorHandler->handleError('???', '???', '???', '???', '???')
#1 vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure('???', '???')
#2 vendor/aki/yii2-bot-telegram/base/Response.php(32): aki\telegram\types\Result->__construct('???')
#3 vendor/yiisoft/yii2/base/Component.php(180): aki\telegram\base\Response->setResult('???')
#4 vendor/yiisoft/yii2/BaseYii.php(558): aki\telegram\base\Response->__set('???', '???')
#5 vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure('???', '???')
#6 vendor/aki/yii2-bot-telegram/Telegram.php(321): aki\telegram\base\Response->__construct('???')
#7 test.php(12): common\components\Telegram\Telegram->setWebhook('???')
```

json response like this:
```
{"ok":true,"result":true,"description":"Webhook is already set"}
```
contains key "result". it to call setter Response::setResult(true).
in this method calling
new Result(true);
but scalar is invalid argument for BaseObject::__construct 
it must be
array $config name-value pairs that will be used to initialize the object properties

**Comment by akbarjoudi** [comment]
The result bug was fixed
