### ISSUE TITLE
aki\telegram\types\Result::author_signature

### ISSUE THREAD

**Issue by c7v** [akbarjoudi/yii2-bot-telegram#39]
Вылетает ошибка при условии если включена подпись сообщений в канале.
```
Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: aki\telegram\types\Result::author_signature'

in /var/www/web/projects/mb_bot/vendor/yiisoft/yii2/base/Component.php:210

Stack trace:
#0 /var/www/web/projects/mb_bot/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('author_signatur...', '\xD0\x9C\xD0\xBE\xD1\x81\xD0\xBA\xD0\xBE\xD0\xB2\xD1\x81\xD0...')
#1 /var/www/web/projects/mb_bot/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(aki\telegram\types\Result), Array)
#2 /var/www/web/projects/mb_bot/vendor/aki/yii2-bot-telegram/base/Response.php(40): yii\base\BaseObject->__construct(Array)
#3 /var/www/web/projects/mb_bot/vendor/yiisoft/yii2/base/Component.php(181): aki\telegram\base\Response->setResult(Array)
#4 /var/www/web/projects/mb_bot/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('result', Array)
#5 /var/www/web/projects/mb_bot/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(aki\telegram\base\Response), Array)
#6 /var/www/web/projects/mb_bot/vendor/aki/yii2-bot-telegram/Telegram.php(43): yii\base\BaseObject->__construct(Array)
#7 /var/www/web/projects/mb_bot/commands/TatnpController.php(29): aki\telegram\Telegram->sendMessage(Array)
#8 [internal function]: app\commands\TatnpController->actionStart()
#9 /var/www/web/projects/mb_bot/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/web/projects/mb_bot/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/web/projects/mb_bot/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('start', Array)
#12 /var/www/web/projects/mb_bot/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('start', Array)
#13 /var/www/web/projects/mb_bot/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('tatnp/start', Array)
#14 /var/www/web/projects/mb_bot/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('tatnp/start', Array)
#15 /var/www/web/projects/mb_bot/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request))
#16 /var/www/web/projects/mb_bot/yii(20): yii\base\Application->run()
#17 {main}

```

**Comment by akbarjoudi** [comment]
@c7v Please tell me what method did you call?

**Comment by c7v** [comment]
> @c7v Please tell me what method did you call?

sendMessage для отправки сообщений

**Comment by akbarjoudi** [comment]
@c7v  The bug was fixed
